### ISSUE TITLE
consider allowing metadata be be a child

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#2]
From discussions with @sogaiu and @borkdude on #slack

When traversing parsed data, the fact that metadata holds the object it is describing can be awkward.

Example from @sogaiu
```Clojure
(defn ns?
  [zloc]
  (when (rz/list? zloc)
    (when-let [head (rz/down zloc)]
      (let [tag (rz/tag head)
            find-ns-name (fn [start-zloc]
                           (let [rzloc (rz/right start-zloc)
                                 r-tag (rz/tag rzloc)]
                             (cond (= r-tag :token)
                                   rzloc
                                   ;;
                                   (= r-tag :meta)
                                   (-> rzloc
                                     rz/down
                                     rz/right)
                                   ;;
                                   :else
                                   nil)))]
        (cond (= tag :token)
              (when (= (rz/string head) "ns")
                (find-ns-name head))
              ;;
              (= tag :meta)
              (let [target (-> head
                             rz/down
                             rz/right)]
                (when (= (rz/string target) "ns")
                  (find-ns-name head)))
              ;;
              :else
              nil)))))
```

Could we allow for metadata to be the child of node instead of the parent node while preserving API compatibility?

**Comment by borkdude** [comment]
@lread In clj-kondo I've opted to include metadata nodes (there can be multiple!) as a `:meta` key-value on the node itself.

**Comment by lread** [comment]
As of this writing (3-Apr-2020), folks on Slack are discussing that default rewrite-clj handling of metadata can be awkward.

@borkdude chimed in:
> yep, something I found annoying in clj-kondo with rewrite-clj as well. I changed the vendored rewrite-clj implementation

And @sogaiu added: 
> the current tree-sitter-clojure grammar implementation puts metadata inside the things they are supposed to be attached to because i found working with rewrite-clj cumbersome wrt metadata 

And also offered [an example from his work on tree-sitter-clojure](https://github.com/sogaiu/tree-sitter-clojure/blob/adb8e0ebbf7490f96270aa93af8a1ce7f5e8b4d8/grammar.js#L338_L352).

**Comment by sogaiu** [comment]
Would very much be interested in discussing how certain things might be done in general (whether it's in a tree-sitter grammar or elsewhere).

Hope you don't mind if I jot down some thoughts here.  If you're not interested / motivated / don't have time / etc. please feel free to ignore :)  I'm also happy to delete this / move it elsewhere.

Anyway, one item that I'm up in the air about is the handling of tagged literals.  They are currently specified as:

https://github.com/sogaiu/tree-sitter-clojure/blob/adb8e0ebbf7490f96270aa93af8a1ce7f5e8b4d8/grammar.js#L434_L449

There are a couple things that might be relevant:

1) To get metadata and discard forms to work, they are pervasive.  Many rules include them as I didn't figure out how to remove that duplication (current hypothesis is that it's a tree-sitter limitation).

2) Tagged literals are "captured" by creating essentially a sequence of tag names followed by some value (ignoring metadata and discard forms for a moment).

I'm mentioning point 1 as my current impression is that there are technical limitations that constrained what's possible with tree-sitter which don't necessarily apply for rewrite-clj*  (This point is mentioned just to give some background.)

The more relevant point is the second one.  I think one could have done some kind of nested capture instead -- that seems logically more like how tagged literals are actually handled / processed in Clojure.  It seemed like that might just add extra work for anyone using a tree though so I didn't go for it -- but there might be a downside I'm not seeing.

If you have any thoughts about this please share :)

**Comment by lread** [comment]
Thanks for this @sogaiu, I don't think I'll comment on this soon, but appreciate your thoughts and research being here to review!

**Comment by sogaiu** [comment]
Thanks for the response and good to hear from you :)

**Comment by lread** [comment]
Effectively transferred to https://github.com/clj-commons/rewrite-clj/issues/115
