### ISSUE TITLE
find-by-last-pos behavior

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#3]
making sure I don't lose this question from @sogaiu on #slack

suppose in ../clojure there is a checkout of clojure and rewrite-clj has been patched to include find-last-by-pos (https://github.com/lread/rewrite-cljs-playground/blob/master/src/rewrite_clj/zip/findz.cljc#L44_L57) (and may be some other things in rewrite-cljs-playground).
consider the following:
```Clojure
(require '[rewrite-clj.zip :as rz])

(def set-str
  (slurp "../clojure/src/clj/clojure/set.clj"))

;; nil
(-> (rz/of-string set-str
          {:track-position? true})
      (rz/find-last-by-pos [1 1]))

;; nil
(-> (rz/of-string set-str
          {:track-position? true})
      (rz/find-last-by-pos [178 1]))
```
the first of the thread-first forms gives nil because the position is before all top-level forms, iiuc.  correspondingly, the second of the thread-first forms gives nil because the position is after all top-level forms.
to distinguish between these cases it appears that comparing the position (e.g. row 1 col 1 or row 178 col 1 in the code above) with the return value of:
```Clojure
(-> (rz/of-string set-str
          {:track-position? true})
      rz/position)
```
is one approach.
anyone know of a better or alternative method?

for some context, i'm doing this sort of thing:
```Clojure
(require '[rewrite-clj.zip :as rz])

  (defn rcb? ; rich comment block
    [zloc]
    (and (rz/list? zloc)
      (= "comment"
        (-> zloc
           rz/down
           rz/string))))

  (defn before?
    [[r1 c1] [r2 c2]]
    (cond (< r1 r2) true
          ;;
          (> r1 r2) false
          ;;
          :else (cond (< c1 c2)
                      true
                      ;;
                      :else
                      false)))

  ;; before
  (before? [1 1] [2 1])

  ;; not before, after
  (before? [5 5] [1 2])
  
  ;; not before, the same
  (before? [10 20] [10 20])

  (defn expr-str-at
    [src-str row col] ; XXX: consider [row col] as single parameter?
    (let [zloc-0 (rz/of-string src-str
                   {:track-position? true})
          _ (assert zloc-0 ; XXX: just return nil instead?
              "of-string returned nil")
          zloc (if-let [zloc (rz/find-last-by-pos zloc-0 [row col])]
                 zloc
                 ;; before or after all top-level forms
                 (let [pos-0 (rz/position zloc-0)]
                   (when (before? pos-0 [row col])
                     (rz/rightmost zloc-0))))]
      (when zloc
        (loop [zloc zloc]
          (if (or (contains? #{:comma :comment :newline :whitespace}
                    (rz/tag zloc))
                (rcb? zloc))
            (recur (rz/left zloc))
            (rz/string zloc))))))
```

it's supposed to find the first non-comment-whitespace-etc expr string "at" row col (where "at" can look left if row col happens to refer to whitespace, newline, comment, comma nodes or (comment ...))

**Comment by sogaiu** [comment]
Here's an attempt at a briefer version of the question:

`find-last-by-pos` returns nil in at least 2 cases -- if the specified position indicates a location before all top-level forms for the zipper in question as well as in the case where the location is after all top-level forms.

nil doesn't tell us which case.

If the zipper in question is retained right after its creation, it can be queried using `position` to determine its "starting point".  That can be compared with whatever was passed as a position to `find-last-by-pos` to distinguish between the cases of being before or after all of the top-level forms.

The question is, is there a better way to achieve the same end (i.e. distinguishing between before and after)?

**Comment by lread** [comment]
Effectively transferred to https://github.com/clj-commons/rewrite-clj/issues/94
