### ISSUE TITLE
Ensure that all line endings are handled successfully

### ISSUE THREAD

**Issue by kkinnear** [lread/rewrite-cljc-playground#62]
**Problem/Opportunity**
It seems that `rewrite-clj` handles a variety of line endings successfully by mapping them all into `\n`.  That is, if you have `\n` or `\r\n` or even `\r` line endings, after parsing, looking at the result of the parse, you get `\n` everywhere.  Which is a fine thing to do.  Except that if you have `\r\n` as the line ending for a comment, you get:

```
zprint.core=> (pst)
AssertionError Assert failed: (string-of? s r/linebreak?)
	rewrite-clj.node.whitespace/newline-node (whitespace.clj:89)
	rewrite-clj.node.whitespace/newline-node (whitespace.clj:89)
	rewrite-clj.parser.whitespace/parse-whitespace (whitespace.clj:12)
	rewrite-clj.parser.whitespace/parse-whitespace (whitespace.clj:6)
	rewrite-clj.parser.core/fn--1963 (core.clj:85)
	rewrite-clj.parser.core/fn--1963 (core.clj:83)
	clojure.lang.MultiFn.invoke (MultiFn.java:229)
	rewrite-clj.reader/read-with-meta (reader.clj:132)
	rewrite-clj.reader/read-with-meta (reader.clj:128)
	rewrite-clj.parser.core/parse-next (core.clj:35)
	rewrite-clj.parser.core/parse-next (core.clj:33)
	rewrite-clj.parser/parse (parser.clj:13)
```

which is mighty unfriendly.

**Proposed Solution**
It would be nice if `rewrite-cljc` handled all three possible line endings successfully, even in comments.  In `zprint` I'm going to a lot of trouble (and processing time) to work around this failing in `rewrite-clj`  and I'm hoping that I can remove all of that when i convert to `rewrite-cljc`!

**Comment by lread** [comment]
Oh that’s a good one @kkinnear! Thanks for raising it!

I will address.

I suppose ideally rewrite-cljc would just preserve existing line endings, but in the spirit of compatibility with rewrite-clj, I’ll have it convert all to `\n`.

**Comment by kkinnear** [comment]
For what it is worth, at least in my processing, I think converting all line endings to `\n` is actually a win.  While initially I ignored all line endings in zprint, these days zprint has many places and modes where it takes into account incoming line endings.  If all of those places had to deal with several different possible line endings, some with different lengths, it would be pretty crazy.  There might be some way to generalize that, I suppose.  But if `rewrite-cljc` converts it all to `\n`, then all I have to do is figure out what the line endings are at the start, and then fix them up at the end (if they weren't `\n`, which they probably were anyway).  So I'm actually a fan of the way `rewrite-clj` decided to handle this -- except for not working with comments, of course.

**Comment by lread** [comment]
I was thinking of a team who develops on Windows and their newlines are all `\r\n` and maybe they'd be a bit surprised when rewrite-clj converted those newlines to `\n`.  

Having mixed newline variants in a source file is odd, but odd things do happen.

**Comment by lread** [comment]
Effectively transferred to rewrite-clj https://github.com/clj-commons/rewrite-clj/issues/93
