### ISSUE TITLE
Consider discarding Potemkin

### ISSUE THREAD

**Issue by vemv** [lread/rewrite-cljc-playground#67]
**Problem/Opportunity**

Potemkin has problems which you can find summarized in https://github.com/metosin/compojure-api/issues/445 .

Additionally to that link one can find one extra problem associated to it: https://github.com/jonase/eastwood/issues/307

**Proposed Solution**

Offer equivalent namespaces and vars which aren't backed by Potemkin. The mapping would be 1:1 and unperceivable by updated consumers.

In the past I have acoimplished so by implementing a very thin macro akin to `import-vars` but without any of its associated trickery. IIRC the macro boils down to copying metadata from a given var to the other at compile-time.

I've also heard of other people doing the same exact thing.

**Alternative Solutions**

* Structure the API in a more traditional way that doen't need `import-vars`-like functionality at all
    * Breaking, but interestingly one could author a rewrite-clj script that rewrote programs to use the new api

**Action**

> Do you want to be involved with designing, coding and then maintaining a solution, if so let us know!]

(I cannot these days)

**Comment by lread** [comment]
Thanks @vemv, your input is much appreciated!

Here are my [notes on the subject]( https://github.com/lread/rewrite-cljc-playground/blob/master/doc/design/01-merging-rewrite-clj-and-rewrite-cljs.adoc#potemkin-import-vars) (a little of out of date, updates at the time of this writing are: cljdoc, cloverage and clj-kondo (with hooks) now work with rewrite-cljc's import-vars).  

It took a ton of time for me to write a ClojureScript equivalent of import-vars.  That said, that was a fruitful learning experience and sunk costs don't mean we have to stick to using import-vars. 

As to the idea:

> Structure the API in a more traditional way that doen't need import-vars-like functionality at all

One of rewrite-cljc's primary goals is to be mostly compatible with rewrite-clj and rewrite-cljs, so unless that goal changes, we won't  entertain restructuring the API.

**Comment by vemv** [comment]
Hey there @lread, thanks for the answer!

> It took a ton of time for me to write a ClojureScript equivalent of import-vars. That said, that was a fruitful learning experience and sunk costs don't mean we have to stick to using import-vars.

Fortunately one doesn't have to ditch import-vars altogether, but instead I'd suggest to further tweak this macro to make it more conservative:

* don't copy `:ns` metadata
  * confuses Eastwood
  * it also simply isn't faithful to the original semantics of `:ns`
    * Surely it means "the ns of _this_ var", not "the ns of some other var which has been copied to this var"
* don't copy `:file, :line, :column` metadata
  * makes CIDER jump to e.g. `rewrite-cljc.zip.move` instead of `rewrite-cljc.zip`
    * this is what Alex Miller refers to in https://groups.google.com/g/clojure/c/Ng_GXYSrKmI/m/ULKD5cN9BAAJ
  * one could argue that jumping to `rewrite-cljc.zip.move` is more useful (since it contains the actual function definition, and not an intermediate `import-vars` statement)
    * but, by doing so one creates bit of a surprising/"magical" behavior, which reasoning people can't always follow

I tried dissocing the metadata in the right place `rewrite-cljc.potemkin.clojure/meta-with-fixes` and I could indeed obtain all the foreseen tooling benefits.

Worth noting, :doc and :arglists metadata is still preserved (as those keys aren't problematic), so one still gets a decent deal of interactivity without having to jump around so much.

WDYT?

**Comment by lread** [comment]
Thanks @vemv, great to explore this with you!

> don't copy `:file`, `:line`, `:column` metadata 

For cljdoc, for example, we want to link to the actual source of the var, there's not much benefit to linking to the import target.
But maybe that's what you are talking about under "one could argue..."

> don't copy `:ns` metadata 

I'd have to take a peek at what this would mean (other than the points you already raised!)

I am serious when I say that I'm open to turfing import-vars entirely - if it is causing real problems and confusion for folks.

**Comment by vemv** [comment]
> For cljdoc, for example, we want to link to the actual source of the var, there's not much benefit to linking to the import target.

Got it! Perhaps it'd make sense to have both a `:file` (non-copied) and a `:potemkin/file` (copied) and teach cljdoc to observe `:potemkin/file`. Same for :line and :column.

In a way, both sources of information are useful so IMO it makes sense to expose both. Which one should be the default source is subjective, although you might agree that leaving :file untouched is more transparent and in line with Clojure's default behavior.

> I am serious when I say that I'm open to turfing import-vars entirely

No strong preferece from my side, as it's not exceedingly rare to implement something similar to `import-vars` so I'd be optimistic about simply tweaking rewrite-cljc's version :)

**Comment by lread** [comment]
Effectively transferred to rewrite-clj https://github.com/clj-commons/rewrite-clj/issues/98
