### ISSUE TITLE
Replace rewrite-cljc logo with rewrite-clj logo

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#69]
Rewrite-cljc is dead, long live rewrite-clj.

**Comment by lread** [comment]
Current candidate:

![rewrite-clj-logo](https://user-images.githubusercontent.com/967328/104786953-664f1a80-575c-11eb-852c-fcccc9e03be2.png)

Can always change later, at least we have something to start with.

**Comment by sogaiu** [comment]
Looks nice :)

Is there some hidden aspect of "change" in the logo (the looping back)?

**Comment by lread** [comment]
Thanks @sogaiu!

> Is there some hidden aspect of "change" in the logo (the looping back)?

Like the arrow in rewrite-cljc logo, the arrow here supposed suggest rewriting. 
One less character had me struggling with a short arrow and meant I could play with the j.

**Comment by sogaiu** [comment]
Have you tried playing with where the tip of the arrow ends?

For example:

![rewrite-clj-alt](https://user-images.githubusercontent.com/33044872/104798108-53ddeb00-5807-11eb-9ee4-1d02dd99550a.png)

**Comment by lread** [comment]
Had not thought of that, interesting idea!

**Comment by lread** [comment]
Effectively transferred to rewrite-clj https://github.com/clj-commons/rewrite-clj/issues/99
