### ISSUE TITLE
Namespaced element support

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#7]
Namespaced map support needs careful review.

rewrite-cljc picked up where rewrite-clj left off in for namespaced map support.
It adds the missing support for auto-resolved namespaced keywords.  

I also added namespaced map support for ClojureScript.  I took inspiration from clojure.tools.reader's cljs side, but left my work unfinished.

To think about

- [x] think about namespaced map support from a parsing perspective 
- [x] think about namespaced map support from sexpr perspective.  Do we really need support for this?  I ask because it does complicate things especially from the cljs side.
- [ ] if we do support sexpr for cljs, weigh different options for specifying an alias-map
  - [ ] clojure tools reader uses dynamic var `*alias-map*` do we reuse this? create our own?
  - [ ] another way to go is to pass in an `:alias-map` much the same way we pass in the optional `:track-position?`

**Comment by lread** [comment]
From a parsing perspective, I think we are ok. To consider: It might be useful to easily learn what type of namespaced map was parsed (prefix namespaced map, auto resolve alias, or auto-resolve namespace).  

In a similar vein it would be nice if the namespace-map-node offered constructors that better reflected these different types.  Review this against breaking compatibility with rewrite-clj.  It might make sense in this case and namespaced maps were a late and incomplete addition to rewrite-clj.

**Comment by lread** [comment]
There's an interesting pre-existing and related behavior in rewrite-clj regarding  auto-resolved keywords: https://github.com/xsc/rewrite-clj/issues/21, to recap:

```Clojure
(n/sexpr (p/parse-string "::xyz/foo")) ;; => :xyz/foo
```

**Comment by vemv** [comment]
In case the input helps, there's the use case of wanting to rewrite `::foo/bar` to `::quux/bar`.

I could accomplish that with rewrite-clj by abusing it with `(assoc node :namespaced?  true :string-value (str ":" ...))`, but of course I'd be happy to discard the hack as I migrate to rewrite-cljc, which I'll want especially for the cljs support!

**Comment by lread** [comment]
Yes, input definitely helps @vemv, thank you.

**Comment by borkdude** [comment]
@lread When I added some functions to the clj-kondo [hooks API](https://github.com/borkdude/clj-kondo/blob/master/doc/hooks.md) I also added `map-node` and `map-node?`. 

The predicates just do a simple instance checks + in some cases a check on tag, e.g. for seq nodes and correspond to their producing counterparts.

I noticed that `keyword-node` takes an optional boolean to indicate that it is auto-resolved (i.e. `::foo` or `::foo/bar`). I like this because `keyword-node?` returns `true` for both kinds of keywords. I was wondering if we could do the same for `map-node`:

`(map-node children) ;;=> {... children }`
`(map-node children prefix) ;;=> #:prefix{... children }`
`(map-node children prefix true) ;;=> #::prefix{... children}`

or 

`(map-node children {:prefix prefix :auto-resolve true}) ;;=> #::prefix{... children}` (this style doesn't seem to be in line with the rest of the API functions perhaps)

It would probably be awkward for the hooks API to have `(map-node? ...)` return `false` for namespaced maps.

**Comment by lread** [comment]
Thanks for bringing this up @borkdude, and my apologies for being so slow to respond.

Rewrite-clj has partial namespaced map support implemented under [namespaced-map-node](https://github.com/xsc/rewrite-clj/blob/f515767e4f07f27389ee2885cb459bd87d903887/src/rewrite_clj/node/seq.clj#L112). 
Forgive me if I've got this wrong as I ramp up again: Are you, at least in part, proposing that we migrate namespaced map support to be included under `map-node`?

As you know, I am leery of making breaking changes, but namespaced maps is one area where there will be breaking changes as the current implementation in rewrite-clj is incomplete.

I am not a huge fan of using booleans in function signatures with more than one arg as they are not self-documenting.  That said, as you point out, it is the path already taken by rewrite-clj for the `keyword-node`.

Aside: I think that the rewrite-clj node creation functions were created primarily for the parser;  general usability did not seem to be a priority. I suppose that does not stop us from creating alternate node creation functions that are easier to use.

Do your clj-kondo needs include auto-resolved current namespace maps?  `#::{... children}` If so, in this case would your `prefix` simply be nil?

We can hash out details on Slack if you like.

**Comment by borkdude** [comment]
> Are you, at least in part, proposing that we migrate namespaced map support to be included under map-node?

Yes.

> Namespaced maps is one area where there will be breaking changes as the current implementation in rewrite-clj is incomplete.

Agreed. I think breaking changes are in order here.

> I am not a huge fan of using booleans in function signatures

Good point. Maybe passing the options via a map is better:

``` clojure
(map-node children) ;;=> {... children }
(map-node children {:prefix "prefix"}) ;;=> #:prefix{... children }
(map-node children  {:prefix "prefix" :auto-resolved  true}) ;;=> #::prefix{... children}
```

The reason I want this to be the same node type is to have overall simpler logic for checking if something is a map. I don't see the need for a separate node type. This will also be more consistent with the keyword node.

**Comment by lread** [comment]
Cool, thanks @borkdude! I don't think I'd given serious thought of handling namespaced map nodes under `map-node`.
Maybe I was biased by the existing implementation.

I like your updated signatures. I suppose auto-resolved current namespace maps could be created via:

```Clojure
(map-node children {:auto-resolved  true}) ;;=> #::{... children}
```

I'll dive back into my old design notes on namespaced elements ([currently on a branch](https://github.com/lread/rewrite-cljc-playground/blob/lread-ns-kw-map/doc/design/01-merging-rewrite-clj-and-rewrite-cljs.adoc#namespaced-maps-and-keywords-in-progress)). I'll ping back after some review and updates.

**Comment by lread** [comment]
Ok, after much back-and-forthing and a very long lived branch, we have an initial version of namespaced element support as of this writing, ending with 2b6b4e06970c09e43aec05d35464405b0dd2256d.

It might not be perfect, but won't know what is amiss until I get feedback from more alpha use.

For example, I am currently uncertain passing in auto-resolve opts (current choice) is a better choice than going with a dynamic-var. I've yet to explore what this means for zipper subedits. We'll see how it plays out and adjust as necessary.

Rather than the discussion in this issue, you would be better to refer to doc/design/namespaced-elements.adoc
And doc/01-introduction.adoc for what we came up with.

**Comment by sogaiu** [comment]
For historical convenience (non-master links):

* [Namespaced elements](https://github.com/lread/rewrite-cljc-playground/blob/c09689e955d650fe7564a955ae22a2f02b7352fe/doc/design/namespaced-elements.adoc)
* [Introduction](https://github.com/lread/rewrite-cljc-playground/blob/c09689e955d650fe7564a955ae22a2f02b7352fe/doc/01-introduction.adoc)
