### ISSUE TITLE
GraalVM support

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#9]
It is a goal to verify that rewrite-cljc natively compiles successfully with GraalVM.

My approach has been to natively compile and run all unit tests.  This works well except that GraalVM's `native-image` consumes more RAM than is available on the free tiers of the CI services I'd like to use.  

I have had success on Drone Cloud which offers a very generous 64gb of RAM, but it is Linux only.  

Ideally I'd like to test across platforms, so maybe GitHub Actions would work nicely - if I can get RAM usage under its 7gb.

I've done experiments where tests are compiled and run by namespace, and tests where each individual test is compiled and run.  Ideally, I'd find something in the middle of these two that works.

Another option is to stick with Docker Cloud only for now and wait to see what GraalVM team comes up with.  They are targeting their next release for a reduction of RAM usage.  GraalVM v20.0 is due to in Feb 2020.

**Comment by lread** [comment]
@borkdude shared a strategy with me on Slack that I must try: 

1. build a custom native-image of babashka including rewrite-cljc like other babashka built in libraries
2. run rewrite-cljc test suite using custom native-image of babashka

**Comment by lread** [comment]
rewrite-cljc tests employ test.check which, I suppose, would also have to be added to babashka.

**Comment by borkdude** [comment]
I also have an issue in babashka to add test.check as preparation work for Clojure spec.

**Comment by lread** [comment]
GraalVM tests are now running on GitHub Actions across Windows, Linux and macOS.
At this time only testing with Graal v20.1.0 jdk8 and jdk11.
Did not bother with figuring out how to get Graal jdk8 setup for Windows and therefore skipping that scenario for now.
